// Code generated by GoBoilr; DO NOT EDIT.
package testdata

import (
	j "encoding/json"
)

// -----------------------------------------------------------------------------
// ComplexStruct Accessors
// -----------------------------------------------------------------------------

func (x *ComplexStruct) Name() string {
	return x.Name
}

func (x *ComplexStruct) SetName(v string) bool {
	x.Name = v
	return true
}

func (x *ComplexStruct) Age() int {
	return x.Age
}

func (x *ComplexStruct) SetAge(v int) bool {
	if !x.validateAge(v) {
		return false
	}
	x.Age = v
	return true
}

func (x *ComplexStruct) Tags() []string {
	return x.Tags
}

func (x *ComplexStruct) Metadata() j.RawMessage {
	return x.Metadata
}

func (x *ComplexStruct) SetPtr(v *int) bool {
	x.Ptr = v
	return true
}

// -----------------------------------------------------------------------------
// Base Accessors
// -----------------------------------------------------------------------------

func (x *Base) ID() string {
	return x.ID
}
