// Code generated by GoBoilr; DO NOT EDIT.
package testdata

import (
	j "encoding/json"
)

/*
func NewComplexStruct(base Base, name string, age int, tags []string, metadata j.RawMessage, ptr *int) *ComplexStruct {
	return &ComplexStruct{
		Base: base,
		Name: name,
		Age: age,
		Tags: tags,
		Metadata: metadata,
		Ptr: ptr,
	}
}
*/

// -----------------------------------------------------------------------------
// ComplexStruct Builder
// -----------------------------------------------------------------------------

type ComplexStructBuilder struct {
	target *ComplexStruct
}

func NewComplexStructBuilder() *ComplexStructBuilder {
	return &ComplexStructBuilder{
		target: &ComplexStruct{},
	}
}

func (b *ComplexStructBuilder) Build() *ComplexStruct {
	return b.target
}

func (b *ComplexStructBuilder) Base(v Base) *ComplexStructBuilder {
	b.target.Base = v
	return b
}

func (b *ComplexStructBuilder) Name(v string) *ComplexStructBuilder {
	b.target.Name = v
	return b
}

func (b *ComplexStructBuilder) Age(v int) *ComplexStructBuilder {
	b.target.Age = v
	return b
}

func (b *ComplexStructBuilder) Tags(v []string) *ComplexStructBuilder {
	b.target.Tags = v
	return b
}

func (b *ComplexStructBuilder) Metadata(v j.RawMessage) *ComplexStructBuilder {
	b.target.Metadata = v
	return b
}

func (b *ComplexStructBuilder) Ptr(v *int) *ComplexStructBuilder {
	b.target.Ptr = v
	return b
}
