// Code generated by GoBoilr; DO NOT EDIT.
package testdata

/*
import (
	j "encoding/json"
)

func NewComplexStruct(base Base, name string, age int, tags []string, metadata j.RawMessage, ptr *int) *ComplexStruct {
	return &ComplexStruct{
		Base:     base,
		Name:     name,
		Age:      age,
		Tags:     tags,
		Metadata: metadata,
		Ptr:      ptr,
	}
}
*/
